version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5078:80"
    networks:
      - app-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=tcp:msa2blogserver.database.windows.net,1433;Initial Catalog=blogDb;Persist Security Info=False;User ID=josephchen935;Password=0274406978King;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    volumes:
      - data-protection-keys:/root/.aspnet/DataProtection-Keys

networks:
  app-network:
    driver: bridge

volumes:
  data-protection-keys: