version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5078:80"
    networks:
      - app-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=tcp:;
    volumes:
      - data-protection-keys:/root/.aspnet/DataProtection-Keys

networks:
  app-network:
    driver: bridge

volumes:
  data-protection-keys: